version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${FRONTEND_PORT}:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - frontend_network
      - back-empresa-huevos_backend_network

networks:
  frontend_network:
    driver: bridge
  back-empresa-huevos_backend_network:
    external: true
